# Generated by Django 2.2.4 on 2021-01-21 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
