# Generated by Django 2.2.4 on 2021-01-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='phone_number',
            new_name='owner_pure_phone',
        ),
    ]
