# Generated by Django 2.2.4 on 2021-01-21 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210121_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_users', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
